### ISSUE TITLE
Help & Resources menu is obscured by content panes

### ISSUE THREAD

**Issue by tpolecat** [unisonweb/unison-local-ui#1]
I came here because this is what was linked from the Unison Local menu, but this seems to be the first issue ... ?

In any case the Help & Resources menu is only visible when the main content area is empty.

- release/M4
- MacOS 11.3.1 (20E241)
- Safari 14.1 (16611.1.21.161.6)

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1200131/179573198-f2d6a000-89e3-48c9-8728-5fe5a521b7ea.png">

**Comment by hojberg** [comment]
I think this is fixed in the `main` branch now. Should be part of the next release.
