### ISSUE TITLE
Local UI errors when viewing symbol function operators

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison-local-ui#10]
This came up as a result of a community question from Exericsm. https://forum.exercism.org/t/unison-local-development-how-to/5577. It seems that the local UI cannot render symbol-based function operator names. 

The local UCM `view`, `display` and `find` operations work as expected. Share is also working, it seems. 

To repro, open `ui` and navigate to `base.data.List.++` or any such symbol based names.

**Comment by yoching** [comment]
I checked the codes and sent a PR here🙂
https://github.com/unisonweb/unison-local-ui/pull/11

**Comment by hojberg** [comment]
Fixed by @yoching 🎉
