### ISSUE TITLE
Message 'Unable to load namespace' in the codespace tree

### ISSUE THREAD

**Issue by clojj** [unisonweb/unison-local-ui#5]
Hi,

running ucm (release/M2g) headless with a new (base is pulled) codebase in the local dir, I get the message
'Unable to load namespace'

Searching for definitions works, the tree is not displayed.
Running ucm and them 'ls' lists the base/ namespace correctly

**Comment by clojj** [comment]
used M4 release, now works fine

**Comment by hojberg** [comment]
I suspect this might be a compatibility issue between M2 and the newest base, which I think is migrated to M4. Which version of base is being pulled?

Would it be possible to update to the latest ucm release?

**Comment by clojj** [comment]
yep, it works fine with M4 release, thx
